version: "3.4"

services:
  todomvc:
    build:
      context: ../../
      dockerfile: ./examples/todomvc/Dockerfile
    depends_on:
      - mongodb-docker
      - redis
      - tracing
    ports:
      - 8080:8080
    environment:
      MONGODB_ADDR: mongodb-docker:27017
      REDIS_ADDR: redis:6379
      TRACING_URL: tracing

  mongodb-docker:
    image: bitnami/mongodb:4.4
    ports:
      - 27017:27017
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      ALLOW_EMPTY_PASSWORD: "yes"

  redis:
    image: redis:6.2-alpine3.13
    ports:
      - 6379:6379
    entrypoint: [redis-server, --appendonly yes]

  tracing:
    image: docker.io/jaegertracing/all-in-one:1.16
    ports:
      - 9411:9411
      - 16686:16686
      - 5778:5778
    environment:
      # Enable Zipkin collector compatability.
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
