version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - embeddedstructfieldcheck
    - err113
    - exhaustive
    - exhaustruct
    - fatcontext
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godoclint
    - godot
    - godox
    - gosmopolitan
    - iface
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - prealloc
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
