---
volumes:
  mongodb:

services:
  eventhorizon-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mongodb-docker
      - gpubsub
      - kafka
      - redis
      - nats
    environment:
      MONGODB_ADDR: mongodb-docker:27017
      PUBSUB_EMULATOR_HOST: gpubsub:8793
      KAFKA_ADDR: kafka:9092
      REDIS_ADDR: redis:6379
      NATS_ADDR: nats:4222
    command: [-c, make test test_integration]

  mongodb-docker:
    image: mongo:8.2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: >
        mongosh --eval "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs0', members:[{_id:0, host:'mongodb-docker:27017'}]}).ok }"
      interval: 5s
      start_period: 10s

  mongodb:
    image: mongo:8.2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: >
        mongosh --eval "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs0', members:[{_id:0, host:'localhost:27017'}]}).ok }"
      interval: 5s
      start_period: 10s

  gpubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:513.0.0-emulators
    ports:
      - 8793:8793
    entrypoint:
      [gcloud, beta, emulators, pubsub, start, --host-port=0.0.0.0:8793]

  kafka:
    image: apache/kafka-native:4.0.0
    ports:
      - 9093:9093
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_LISTENERS: HOST://:9093,DOCKER://:9092,CONTROLLER://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9093,DOCKER://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 5
      CLUSTER_ID: eventhorizon-test-kafka

  redis:
    image: redis:8.0.2-alpine
    ports:
      - 6379:6379
    entrypoint: [redis-server, --appendonly yes]

  nats:
    image: nats:2.12.4-alpine
    ports:
      - 4222:4222
    command: [-js]
